export const FETCH_DOGS_REQUEST = "FETCH_DOGS_REQUEST";
export const FETCH_DOGS_SUCCESS = "FETCH_DOGS_SUCCESS";
export const FETCH_DOGS_FAILURE = "FETCH_DOGS_FAILURE";
export const FETCH_DOGS_BY_ID_SUCCESS = "FETCH_DOGS_BY_ID_SUCCESS";
